// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.21.12
// source: protos/account/info.proto

package account

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetUserInfoByTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationSecret string `protobuf:"bytes,1,opt,name=applicationSecret,proto3" json:"applicationSecret,omitempty"`
	Token             string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetUserInfoByTokenRequest) Reset() {
	*x = GetUserInfoByTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoByTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByTokenRequest) ProtoMessage() {}

func (x *GetUserInfoByTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByTokenRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoByTokenRequest) Descriptor() ([]byte, []int) {
	return file_protos_account_info_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserInfoByTokenRequest) GetApplicationSecret() string {
	if x != nil {
		return x.ApplicationSecret
	}
	return ""
}

func (x *GetUserInfoByTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUserInfoByTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountUrl   string `protobuf:"bytes,2,opt,name=accountUrl,proto3" json:"accountUrl,omitempty"`
	EncodeUserId string `protobuf:"bytes,4,opt,name=encodeUserId,proto3" json:"encodeUserId,omitempty"`
	Nickname     string `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar       string `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender       string `protobuf:"bytes,10,opt,name=gender,proto3" json:"gender,omitempty"`
}

func (x *GetUserInfoByTokenResponse) Reset() {
	*x = GetUserInfoByTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoByTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByTokenResponse) ProtoMessage() {}

func (x *GetUserInfoByTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByTokenResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoByTokenResponse) Descriptor() ([]byte, []int) {
	return file_protos_account_info_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserInfoByTokenResponse) GetAccountUrl() string {
	if x != nil {
		return x.AccountUrl
	}
	return ""
}

func (x *GetUserInfoByTokenResponse) GetEncodeUserId() string {
	if x != nil {
		return x.EncodeUserId
	}
	return ""
}

func (x *GetUserInfoByTokenResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserInfoByTokenResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetUserInfoByTokenResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

var File_protos_account_info_proto protoreflect.FileDescriptor

var file_protos_account_info_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x5f,
	0x0a, 0x19, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0xac, 0x01, 0x0a, 0x1a, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42,
	0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x22,
	0x0a, 0x0c, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x32, 0x79,
	0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x71, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2c, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x67,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protos_account_info_proto_rawDescOnce sync.Once
	file_protos_account_info_proto_rawDescData = file_protos_account_info_proto_rawDesc
)

func file_protos_account_info_proto_rawDescGZIP() []byte {
	file_protos_account_info_proto_rawDescOnce.Do(func() {
		file_protos_account_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_account_info_proto_rawDescData)
	})
	return file_protos_account_info_proto_rawDescData
}

var file_protos_account_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_account_info_proto_goTypes = []interface{}{
	(*GetUserInfoByTokenRequest)(nil),  // 0: grpc.account.info.getUserInfoByTokenRequest
	(*GetUserInfoByTokenResponse)(nil), // 1: grpc.account.info.getUserInfoByTokenResponse
}
var file_protos_account_info_proto_depIdxs = []int32{
	0, // 0: grpc.account.info.info.GetUserInfoByToken:input_type -> grpc.account.info.getUserInfoByTokenRequest
	1, // 1: grpc.account.info.info.GetUserInfoByToken:output_type -> grpc.account.info.getUserInfoByTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_account_info_proto_init() }
func file_protos_account_info_proto_init() {
	if File_protos_account_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_account_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoByTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoByTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_account_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_account_info_proto_goTypes,
		DependencyIndexes: file_protos_account_info_proto_depIdxs,
		MessageInfos:      file_protos_account_info_proto_msgTypes,
	}.Build()
	File_protos_account_info_proto = out.File
	file_protos_account_info_proto_rawDesc = nil
	file_protos_account_info_proto_goTypes = nil
	file_protos_account_info_proto_depIdxs = nil
}
