// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.21.12
// source: protos/account/oauth.proto

package account

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetSignInUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationSecret string `protobuf:"bytes,1,opt,name=applicationSecret,proto3" json:"applicationSecret,omitempty"`
}

func (x *GetSignInUrlRequest) Reset() {
	*x = GetSignInUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_oauth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSignInUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignInUrlRequest) ProtoMessage() {}

func (x *GetSignInUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_oauth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignInUrlRequest.ProtoReflect.Descriptor instead.
func (*GetSignInUrlRequest) Descriptor() ([]byte, []int) {
	return file_protos_account_oauth_proto_rawDescGZIP(), []int{0}
}

func (x *GetSignInUrlRequest) GetApplicationSecret() string {
	if x != nil {
		return x.ApplicationSecret
	}
	return ""
}

type GetSignInUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignInUrl string `protobuf:"bytes,2,opt,name=signInUrl,proto3" json:"signInUrl,omitempty"`
}

func (x *GetSignInUrlResponse) Reset() {
	*x = GetSignInUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_oauth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSignInUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignInUrlResponse) ProtoMessage() {}

func (x *GetSignInUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_oauth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignInUrlResponse.ProtoReflect.Descriptor instead.
func (*GetSignInUrlResponse) Descriptor() ([]byte, []int) {
	return file_protos_account_oauth_proto_rawDescGZIP(), []int{1}
}

func (x *GetSignInUrlResponse) GetSignInUrl() string {
	if x != nil {
		return x.SignInUrl
	}
	return ""
}

var File_protos_account_oauth_proto protoreflect.FileDescriptor

var file_protos_account_oauth_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2f, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x6f, 0x61, 0x75, 0x74, 0x68,
	0x22, 0x43, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x55, 0x72, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x11, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x34, 0x0a, 0x14, 0x67, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e,
	0x49, 0x6e, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x55, 0x72, 0x6c, 0x32, 0x6a, 0x0a, 0x05, 0x6f,
	0x61, 0x75, 0x74, 0x68, 0x12, 0x61, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x49,
	0x6e, 0x55, 0x72, 0x6c, 0x12, 0x27, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x2e, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x67, 0x65, 0x74, 0x53, 0x69, 0x67,
	0x6e, 0x49, 0x6e, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x6f, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x67, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x55, 0x72, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_account_oauth_proto_rawDescOnce sync.Once
	file_protos_account_oauth_proto_rawDescData = file_protos_account_oauth_proto_rawDesc
)

func file_protos_account_oauth_proto_rawDescGZIP() []byte {
	file_protos_account_oauth_proto_rawDescOnce.Do(func() {
		file_protos_account_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_account_oauth_proto_rawDescData)
	})
	return file_protos_account_oauth_proto_rawDescData
}

var file_protos_account_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_account_oauth_proto_goTypes = []interface{}{
	(*GetSignInUrlRequest)(nil),  // 0: grpc.account.oauth.getSignInUrlRequest
	(*GetSignInUrlResponse)(nil), // 1: grpc.account.oauth.getSignInUrlResponse
}
var file_protos_account_oauth_proto_depIdxs = []int32{
	0, // 0: grpc.account.oauth.oauth.GetSignInUrl:input_type -> grpc.account.oauth.getSignInUrlRequest
	1, // 1: grpc.account.oauth.oauth.GetSignInUrl:output_type -> grpc.account.oauth.getSignInUrlResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_account_oauth_proto_init() }
func file_protos_account_oauth_proto_init() {
	if File_protos_account_oauth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_account_oauth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSignInUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_oauth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSignInUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_account_oauth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_account_oauth_proto_goTypes,
		DependencyIndexes: file_protos_account_oauth_proto_depIdxs,
		MessageInfos:      file_protos_account_oauth_proto_msgTypes,
	}.Build()
	File_protos_account_oauth_proto = out.File
	file_protos_account_oauth_proto_rawDesc = nil
	file_protos_account_oauth_proto_goTypes = nil
	file_protos_account_oauth_proto_depIdxs = nil
}
